title: Deepak Agarwal # your name (or website title) here
logo: "/download-circular.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Full-Stack Developer | Front End Developer | Web Developer
  <br><br>
  <a href="mailto:dennisagarwal@gmail.com">dennisagarwal@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/deepakagarwal04/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/dennisagarwal/">Gihub</a> 
   <br>
   <a href="https://drive.google.com/file/d/17C_qVEy7fNoanqfRddxZ4IdqrrwyM7CK/view?usp=sharing"><button>Deepak Aagarwal Resume Download<button></a> 
theme: jekyll-theme-minimal
