title: Deepak Agarwal # your name (or website title) here
logo: "/profil.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Full-Stack Developer
  <br><br>
  <a href="mailto:dennisagarwal@gmail.com">aashima.ahuja811@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/deepakagarwal04/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/dennisagarwal/">Gihub</a> 
  theme: jekyll-theme-cayman
